* Lab 1 - Projection - Report

** Section 1   

   - Projection 1 - California State Plane III
   - Projection 2 - California State Plant IV
   - Projection 3 - Continental US - Albers Conic
   - Projection 4 - Hawaii
|             | CA State Plane III | CA state plane III | CA state plane IV | CA State Plane IV | US- Albers Conic | US - Albers Conic |       Hawaii |   Hawaii |
|             |        Distance(m) |            Bearing |       Distance(m) |           Bearing |      Distance(m) |           Bearing | Distance (m) |  Bearing |
|-------------+--------------------+--------------------+-------------------+-------------------+------------------+-------------------+--------------+----------|
| SF-Oakland  |       13427.114736 |           76.08475 |       13468.69223 |          76.08827 |     13313.129201 |          75.82542 | 14741.014902 | 78.62318 |
| SF-South SF |       13353.053029 |           175.8291 |      13393.025585 |          175.8284 |     13483.218558 |           175.911 |   12070.4947 | 174.8898 |


*** Questions

    1. Is the ratio similar for both city pairs? Explain the reason using
   characteristics of conformal projections. 
   
   |             | Distance Ratio                      |
   |-------------+-------------------------------------|
   | SF-Oakland  | 13468.69223/13427.114736 = 1.00309  |
   | SF-South SF | 13393.025585/13353.053029 = 1.00299 |

   Ratio does look similar. Conformal projections tend to preserve the
   shape of the features but compromizes the size of the features. The
   distance measurement being preserved between the two projections is
   an expected outcome of comparing conformal projections. 

   2. Calculate the distance ratio for projection 4 vs. projection 3.
     Is the ratio similar for both city pairs? Explain the reason
     using characteristics of equal area projections.

     |             | Distance Ratio                      |
     |-------------+-------------------------------------|
     | SF-Oakland  | 14741.014902/13313.129201 = 1.10725 |
     | SF-South SF | 12090.4947/13483.218558 = 0.89670   |
     
     Ratio is not similar. Reason: Equal area projection preserves the
     size of the features by compromizing the shape of the features on
     the map. Distance measurement is prone to differences in changes
     in the shape of the features.

   3. Did the bearing values change between projection 1 and
      projection 2? Explain the reason using characteristics of
      conformal projections.

     Bearing value changed very little (approx ~0.004). Bearing did
      not change much between the conformal projetions since the shape
      of the features was preserved between the projections and
      bearing is a feature that is prone to changes in shape.

   - Did the bearing values change between projection 3 and projection
     4? Explain the reason using characteristics of equal area
     projections.
     
     Bearing values did change, especially noticeable between SF and Oakland
     projections(magnitude of 3). Equal area projections does not
     preserve shape which bearing relies on.

** Section 3: Computing area measurements
|               | /Projection 1/ | /Projection 2/ | /Projection 3/ | /Projection 4/ |
|---------------+----------------+----------------+----------------+----------------|
|               | /Area (acres)/ | /Area (acres)/ | /Area (acres)/ | /Area (acres)/ |
| /Muir Woods/  |     490.632498 |     493.822755 |     490.698786 |     490.696565 |
| /Joshua Tree/ |  738338.037075 |  735225.583707 |  735213.550687 |  735212.090587 |


   
*** Questions
    1. Ratio of area projection 2/projection 1

       Muir woods - 493.822755/490.632498 = 1.00656
       There is a difference in area between projection 1 and
       projection 2. A difference with magnitude of 3 acres. This is
       because conformal projections do not preserve the size between
       projections. Area of the polygon relies on the shape. So,
       conformal projections showing variations is expected.

    2. Ratio of area projection 2/projection 1
       
       Joshua tree - 735225.583707/738338.037075 = 0.99578
       There is a 3 acre difference in magnitude between the
       projections for Joshua tree. Since conformal projections don't
       preserve size between projections, area differs between projections

    3. Ratio of projection 3 vs projection 4

       Muir woods - 490.698786 / 490.696565 = 1.00000
       Joshua tree - 735213.550687 / 735212.090587 = 1.00000
       Equal area projections preserve the size of the features
       between projections. So the area of the polygon(Joshua tree)
       didn't vary too much between projections.

** Section 4: Verifying Custom projection   

*** Stereographic 1(Central Meridian: -122 and Latitude of origin 38)
 |             |     Distance |  Bearing |
 |-------------+--------------+----------|
 | SF-Oakland  | 13428.025189 | 76.09039 |
 | SF-South SF |  13353.97096 | 175.8345 |

*** Stereographic 2(CM: -122, Latitude of origin: 43)
|             |     Distance |  Bearing |
|-------------+--------------+----------|
| SF-Oakland  | 13451.839698 | 76.08731 |
| SF-south SF | 13378.409494 | 175.8338 |

*** Questions
    1. Is the ratio similar for both city pairs? Explain the reason
       using characteristics of conformal projections.

       SF-Oakland Distance Ratio: Proj2/ Proj1 : 1.00177
       SF-South SF Distance Ratio: Proj2/Proj1 : 1.00183
       
       The ratio is similar for both city pairs. The stereographic
       projections are conformal projection that preserve the shape of
       the projections over the size. Distance measurement is
       preserved between conformal projections
       

    2. Did the bearing values change between projection 1 and
       projection 2? Explain the reason using characteristics of
       conformal projections.

       SF-Oakland Bearing ratio: Proj 2/ Proj 1 : 76.08731/76.09039 = 0.99959
       SF-South SF Bearing ration: Proj 2/ Proj 1 :
       175.8338/175.8345 = 0.99999

       Bearing didn't change too much between projections and this is
       an expected outcome of using conformal projection and verifies
       stereographic projections are conformal.



    

